# Generated by Django 5.2.6 on 2025-10-07 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractwork',
            old_name='buyer',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='contractwork',
            name='seller',
        ),
        migrations.AddField(
            model_name='contractwork',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
