# Generated by Django 5.2.6 on 2025-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='theme',
            field=models.TextField(default='Default theme'),
            preserve_default=False,
        ),
    ]
