# Generated by Django 5.2.6 on 2025-10-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='license_text',
            new_name='lyrics_text',
        ),
        migrations.AddField(
            model_name='product',
            name='license_type',
            field=models.CharField(choices=[('royalty_free', 'Royalty-free'), ('non_exclusive', 'Non-exclusive'), ('exclusive', 'Exclusive')], default='non_exclusive', max_length=20),
        ),
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.genre'),
        ),
    ]
